// All UI text lives here so an English file can be added later with the same keys.
export const de = {
  appName: 'Spermio',
  common: {
    continue: 'Weiter',
    cancel: 'Abbrechen',
    back: 'Zurück',
    lock: 'Sperren',
    save: 'Speichern',
    working: 'Einen Moment …',
  },
  install: {
    title: 'App zum Home-Bildschirm hinzufügen',
    intro: 'Patientendaten werden nur auf diesem Gerät gespeichert. Damit Safari sie nicht automatisch löscht, muss die App installiert sein.',
    iosSteps: [
      'Tippe unten in Safari auf das Teilen-Symbol (Quadrat mit Pfeil).',
      'Wähle „Zum Home-Bildschirm“.',
      'Öffne die App danach über das neue Symbol auf dem Home-Bildschirm.',
    ],
    otherSteps: [
      'Öffne das Browser-Menü.',
      'Wähle „App installieren“ bzw. „Zum Startbildschirm hinzufügen“.',
      'Öffne die App danach über das neue Symbol.',
    ],
    testAnyway: 'Nur testen, ohne Installation (keine echten Daten!)',
    notInstalledBanner: 'Testmodus im Browser – keine echten Patientendaten eingeben.',
  },
  testMode: {
    banner: 'Testversion – ohne Passwort. Nur Testdaten eingeben, keine echten Patientinnen.',
  },
  setup: {
    title: 'Willkommen',
    intro: 'Lege ein App-Passwort fest. Es schützt alle Daten auf diesem Gerät.',
    password: 'App-Passwort',
    passwordRepeat: 'Passwort wiederholen',
    tooShort: 'Mindestens 10 Zeichen.',
    mismatch: 'Die Passwörter stimmen nicht überein.',
    create: 'Passwort festlegen',
  },
  recovery: {
    title: 'Dein Wiederherstellungscode',
    intro: 'Wenn du dein Passwort vergisst, ist dieser Code der einzige Weg zurück an deine Daten. Niemand sonst – auch nicht der Entwickler – kann sie wiederherstellen.',
    howTo: 'Drucke den Code aus oder schreibe ihn ab und bewahre ihn sicher auf (nicht nur auf diesem Handy).',
    copy: 'Code kopieren',
    copied: 'Kopiert',
    print: 'Drucken',
    confirmCheck: 'Ich habe den Code ausgedruckt oder sicher aufgeschrieben.',
    verifyLabel: (n: number) => `Zur Kontrolle: Gib den ${n}. Block des Codes ein`,
    verifyWrong: 'Dieser Block stimmt nicht. Bitte prüfe deine Notiz.',
  },
  persist: {
    denied: 'Achtung: Der Browser hat dauerhaften Speicher abgelehnt. Daten könnten bei Speichermangel gelöscht werden. Erstelle regelmäßig Backups.',
  },
  unlock: {
    title: 'Gesperrt',
    password: 'App-Passwort',
    submit: 'Entsperren',
    wrong: 'Falsches Passwort.',
    forgot: 'Passwort vergessen?',
  },
  recover: {
    title: 'Mit Wiederherstellungscode entsperren',
    code: 'Wiederherstellungscode',
    newPassword: 'Neues App-Passwort',
    submit: 'Entsperren und Passwort ändern',
    wrong: 'Dieser Code ist nicht gültig.',
  },
  home: {
    title: 'Übersicht',
    patients: 'Patientinnen',
    empty: 'Noch keine Patientinnen. Lade Demo-Daten, um die App auszuprobieren.',
    loadDemo: 'Demo-Daten laden',
    demoLoaded: (n: number) => `${n} Demo-Patientinnen angelegt.`,
    dueDate: 'ET',
    visits: (n: number) => (n === 1 ? '1 Besuch' : `${n} Besuche`),
    children: (n: number) => (n === 1 ? '1 Kind' : `${n} Kinder`),
    statuses: { pending: 'Neu', active: 'In Betreuung', archived: 'Archiv' },
  },
  patient: {
    add: '+ Neue Patientin',
    newTitle: 'Neue Patientin',
    editTitle: 'Patientin bearbeiten',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    deleteConfirm: 'Wirklich löschen?',
    timeline: 'Verlauf',
    noEntries: 'Noch keine Einträge.',
    addVisit: '+ Besuch',
    addChild: '+ Kind',
    addNote: '+ Notiz',
    contact: 'Kontakt',
    insurance: 'Versicherung',
    phase: 'Aktuelle Phase',
    born: 'Geburt',
    note: 'Notiz',
    visit: 'Besuch',
    minutes: 'Min.',
    km: 'km',
  },
  visit: {
    newTitle: 'Neuer Besuch',
    editTitle: 'Besuch bearbeiten',
    duration: 'Dauer',
    motherVitals: 'Mutter (optional)',
    childVitals: 'Kind (optional)',
    billing: 'Leistungen',
    noPositions: 'Für diese Phase gibt es keine Positionen.',
    sampleTariff: 'Beispiel-Tarif – nicht offiziell',
    endBeforeStart: 'Ende liegt vor dem Beginn.',
  },
  child: { newTitle: 'Neues Kind', editTitle: 'Kind bearbeiten' },
  note: { newTitle: 'Neue Notiz', editTitle: 'Notiz bearbeiten' },
  fields: {
    personal: 'Persönliche Daten',
    firstName: 'Vorname',
    lastName: 'Nachname',
    dateOfBirth: 'Geburtsdatum',
    street: 'Straße und Hausnummer',
    postcode: 'PLZ',
    city: 'Ort',
    phone: 'Telefon',
    email: 'E-Mail',
    insuranceType: 'Versicherungsart',
    insurerName: 'Krankenkasse / Versicherung',
    insuranceNumber: 'Versichertennummer',
    pregnancy: 'Schwangerschaft',
    dueDate: 'Errechneter Termin (ET)',
    services: 'Gewünschte Leistungen',
    preferredContact: 'Bevorzugter Kontaktweg',
    message: 'Nachricht',
    status: 'Status',
    date: 'Datum',
    startTime: 'Beginn',
    endTime: 'Ende',
    location: 'Ort des Kontakts',
    seen: 'Betreut wurde',
    whichChild: 'Welches Kind',
    phase: 'Betreuungsphase',
    bp: 'Blutdruck (z. B. 120/80)',
    pulse: 'Puls',
    temp: 'Temperatur (°C)',
    weightKg: 'Gewicht (kg)',
    weightG: 'Gewicht (g)',
    feeding: 'Ernährung',
    childNotes: 'Notizen zum Kind',
    notes: 'Notizen',
    travelKm: 'Wegstrecke (km)',
    childName: 'Name',
    sex: 'Geschlecht',
    birthDate: 'Geburtsdatum',
    birthTime: 'Geburtszeit',
    birthWeightG: 'Geburtsgewicht (g)',
    lengthCm: 'Länge (cm)',
    headCm: 'Kopfumfang (cm)',
    apgar1: 'APGAR 1 Min.',
    apgar5: 'APGAR 5 Min.',
    apgar10: 'APGAR 10 Min.',
    birthMode: 'Geburtsmodus',
    placeOfBirth: 'Geburtsort',
    childInsurer: 'Krankenkasse des Kindes',
    childInsuranceNumber: 'Versichertennummer des Kindes',
    text: 'Text',
    required: 'Bitte ausfüllen',
  },
  options: {
    insuranceType: { statutory: 'Gesetzlich', private: 'Privat' },
    services: {
      pregnancy: 'Schwangerenvorsorge',
      birthPrep: 'Geburtsvorbereitungskurs',
      postpartum: 'Wochenbettbetreuung',
      breastfeeding: 'Stillberatung',
      recovery: 'Rückbildungskurs',
    },
    preferredContact: { phone: 'Telefon', email: 'E-Mail', sms: 'SMS' },
    status: { pending: 'Neu', active: 'In Betreuung', archived: 'Archiv' },
    location: { home: 'Hausbesuch', practice: 'Praxis', video: 'Video', phone: 'Telefon' },
    seen: { mother: 'Mutter', child: 'Kind', both: 'Mutter und Kind' },
    phase: { pregnancy: 'Schwangerschaft', birth: 'Geburt', postpartum: 'Wochenbett' },
    sex: { female: 'weiblich', male: 'männlich', diverse: 'divers' },
    birthMode: { spontan: 'Spontan', vaginal_op: 'Vaginal-operativ', sectio: 'Kaiserschnitt' },
    placeOfBirth: { clinic: 'Klinik', birthCenter: 'Geburtshaus', home: 'Hausgeburt' },
  },
  settings: {
    title: 'Einstellungen',
    changePassword: 'Passwort ändern',
    oldPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort',
    passwordChanged: 'Passwort geändert.',
    wrongPassword: 'Aktuelles Passwort ist falsch.',
    diagnostics: 'Diagnose exportieren',
    diagnosticsHint: 'Enthält nur App-Version, Fehler und Anzahl der Einträge – keine Patientendaten.',
    wipe: 'Alle Daten auf diesem Gerät löschen',
    wipeConfirm: 'Zum Bestätigen LÖSCHEN eingeben',
    wipeWord: 'LÖSCHEN',
    autoLock: 'Automatische Sperre nach 5 Minuten Inaktivität.',
  },
} as const;

export const t = de;
