// All UI text lives here so an English file can be added later with the same keys.
export const de = {
  appName: 'Spermio',
  common: {
    continue: 'Weiter',
    cancel: 'Abbrechen',
    back: 'Zurück',
    lock: 'Sperren',
    save: 'Speichern',
    working: 'Einen Moment …',
  },
  install: {
    title: 'App zum Home-Bildschirm hinzufügen',
    intro: 'Patientendaten werden nur auf diesem Gerät gespeichert. Damit Safari sie nicht automatisch löscht, muss die App installiert sein.',
    iosSteps: [
      'Tippe unten in Safari auf das Teilen-Symbol (Quadrat mit Pfeil).',
      'Wähle „Zum Home-Bildschirm“.',
      'Öffne die App danach über das neue Symbol auf dem Home-Bildschirm.',
    ],
    otherSteps: [
      'Öffne das Browser-Menü.',
      'Wähle „App installieren“ bzw. „Zum Startbildschirm hinzufügen“.',
      'Öffne die App danach über das neue Symbol.',
    ],
    testAnyway: 'Nur testen, ohne Installation (keine echten Daten!)',
    notInstalledBanner: 'Testmodus im Browser – keine echten Patientendaten eingeben.',
  },
  testMode: {
    banner: 'Testversion – ohne Passwort. Nur Testdaten eingeben, keine echten Patientinnen.',
  },
  setup: {
    title: 'Willkommen',
    intro: 'Lege ein App-Passwort fest. Es schützt alle Daten auf diesem Gerät.',
    password: 'App-Passwort',
    passwordRepeat: 'Passwort wiederholen',
    tooShort: 'Mindestens 10 Zeichen.',
    mismatch: 'Die Passwörter stimmen nicht überein.',
    create: 'Passwort festlegen',
  },
  recovery: {
    title: 'Dein Wiederherstellungscode',
    intro: 'Wenn du dein Passwort vergisst, ist dieser Code der einzige Weg zurück an deine Daten. Niemand sonst – auch nicht der Entwickler – kann sie wiederherstellen.',
    howTo: 'Drucke den Code aus oder schreibe ihn ab und bewahre ihn sicher auf (nicht nur auf diesem Handy).',
    copy: 'Code kopieren',
    copied: 'Kopiert',
    print: 'Drucken',
    confirmCheck: 'Ich habe den Code ausgedruckt oder sicher aufgeschrieben.',
    verifyLabel: (n: number) => `Zur Kontrolle: Gib den ${n}. Block des Codes ein`,
    verifyWrong: 'Dieser Block stimmt nicht. Bitte prüfe deine Notiz.',
  },
  persist: {
    denied: 'Achtung: Der Browser hat dauerhaften Speicher abgelehnt. Daten könnten bei Speichermangel gelöscht werden. Erstelle regelmäßig Backups.',
  },
  unlock: {
    title: 'Gesperrt',
    password: 'App-Passwort',
    submit: 'Entsperren',
    wrong: 'Falsches Passwort.',
    forgot: 'Passwort vergessen?',
  },
  recover: {
    title: 'Mit Wiederherstellungscode entsperren',
    code: 'Wiederherstellungscode',
    newPassword: 'Neues App-Passwort',
    submit: 'Entsperren und Passwort ändern',
    wrong: 'Dieser Code ist nicht gültig.',
  },
  home: {
    title: 'Übersicht',
    patients: 'Patientinnen',
    empty: 'Noch keine Patientinnen. Lege oben eine neue an.',
    loadDemo: 'Demo-Daten laden',
    demoLoaded: (n: number) => `${n} Demo-Patientinnen angelegt.`,
    removeDemo: 'Demo-Daten entfernen',
    demoRemoved: (n: number) => `${n} Demo-Patientinnen entfernt.`,
    demoTitle: 'Demo-Daten',
    demoHint: 'Fünf erfundene Patientinnen mit Besuchen – praktisch, um Abrechnung zu testen.',
    dueDate: 'ET',
    visits: (n: number) => (n === 1 ? '1 Besuch' : `${n} Besuche`),
    children: (n: number) => (n === 1 ? '1 Kind' : `${n} Kinder`),
    statuses: { pending: 'Neu', active: 'In Betreuung', archived: 'Archiv' },
  },
  patient: {
    add: '+ Neue Patientin',
    newTitle: 'Neue Patientin',
    editTitle: 'Patientin bearbeiten',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    deleteConfirm: 'Wirklich löschen?',
    timeline: 'Verlauf',
    noEntries: 'Noch keine Einträge.',
    addVisit: '+ Besuch',
    addChild: '+ Kind',
    addNote: '+ Notiz',
    contact: 'Kontakt',
    insurance: 'Versicherung',
    phase: 'Aktuelle Phase',
    born: 'Geburt',
    note: 'Notiz',
    visit: 'Besuch',
    minutes: 'Min.',
    km: 'km',
  },
  visit: {
    newTitle: 'Neuer Besuch',
    editTitle: 'Besuch bearbeiten',
    duration: 'Dauer',
    motherVitals: 'Mutter (optional)',
    childVitals: 'Kind (optional)',
    billing: 'Leistungen',
    noPositions: 'Für diese Phase gibt es keine Positionen.',
    tariffNote: 'Hebammenhilfevertrag, Vergütung ab 01.11.2025',
    materials: 'Materialpauschalen',
    notForArt: 'nicht für diese Kontaktart',
    endBeforeStart: 'Ende liegt vor dem Beginn.',
  },
  invoice: {
    add: '+ Rechnung',
    list: 'Rechnungen',
    newTitle: 'Neue Rechnung',
    title: 'Rechnung',
    payer: 'Rechnung an',
    insured: 'Versicherte/r',
    from: 'Von',
    to: 'Bis',
    period: 'Zeitraum',
    issued: 'Rechnungsdatum',
    total: 'Gesamt',
    nothing: 'Keine abrechenbaren Besuche in diesem Zeitraum.',
    create: 'Rechnung erstellen',
    pdf: 'PDF',
    csv: 'CSV',
    status: 'Status',
    statuses: { draft: 'Entwurf', sent: 'Versendet', paid: 'Bezahlt' },
    delete: 'Rechnung löschen',
    deleteConfirm: 'Rechnung löschen? Die Besuche werden wieder abrechenbar.',
    practiceMissing: 'Tipp: Trage unter ⚙︎ Einstellungen deine Praxisdaten (Name, IK-Nummer) ein, damit sie auf der Rechnung stehen.',
  },
  intake: {
    title: 'Anmeldung bei deiner Hebamme',
    intro: 'Bitte fülle das Formular aus. Deine Angaben werden auf deinem Gerät verschlüsselt und können nur von deiner Hebamme gelesen werden.',
    consent: 'Ich habe die Datenschutzhinweise gelesen und bin mit der Verarbeitung meiner Daten zur Hebammenbetreuung einverstanden.',
    privacyTitle: 'Datenschutzhinweise',
    privacyText: 'PLATZHALTER – Hier kommt der Datenschutztext der Hebamme hin (Verantwortliche, Zweck, Speicherdauer, Rechte). Testversion.',
    consentMissing: 'Bitte bestätige die Datenschutzhinweise.',
    submit: 'Verschlüsselt absenden',
    sending: 'Wird verschlüsselt und gesendet …',
    done: 'Danke! Deine Anmeldung ist bei deiner Hebamme angekommen. Sie meldet sich bei dir.',
    badLink: 'Dieser Link ist unvollständig oder ungültig. Bitte frage deine Hebamme nach einem neuen Link.',
    keyMismatch: 'Sicherheitsprüfung fehlgeschlagen: Der Schlüssel passt nicht zum Link. Bitte nichts absenden und die Hebamme informieren.',
    failed: 'Senden hat nicht geklappt. Bitte prüfe deine Internetverbindung und versuche es erneut.',
  },
  inbox: {
    title: 'Online-Anmeldung',
    hint: 'Schicke diesen Link an Schwangere. Ihre Angaben kommen verschlüsselt hier an.',
    share: 'Formular-Link teilen',
    copied: 'Link kopiert.',
    check: 'Neue Anmeldungen abrufen',
    imported: (n: number) => (n === 0 ? 'Keine neuen Anmeldungen.' : n === 1 ? '1 neue Anmeldung importiert.' : `${n} neue Anmeldungen importiert.`),
    offline: 'Anmeldungen konnten nicht abgerufen werden (offline?).',
    pendingTitle: 'Neue Online-Anmeldung',
    pendingHint: 'Bitte prüfen und annehmen oder ablehnen.',
    accept: 'Annehmen',
    reject: 'Ablehnen',
    rejectConfirm: 'Anmeldung ablehnen und löschen?',
  },
  backup: {
    title: 'Automatisches Backup',
    hint: 'Nach jeder Änderung wird eine verschlüsselte Kopie gesichert. Niemand außer dir kann sie lesen.',
    last: (when: string) => `Letztes Backup: ${when}`,
    never: 'Noch kein Backup.',
    now: 'Jetzt sichern',
    done: 'Backup gespeichert.',
    failed: 'Backup fehlgeschlagen (offline?). Wird automatisch wiederholt.',
    showCode: 'Backup-Code anzeigen',
    codeHint: 'Mit diesem Code holst du alle Daten auf ein neues Handy. Schreibe ihn auf und bewahre ihn getrennt vom Handy auf.',
    confirm: 'Ich habe den Code notiert',
    bannerCode: 'Backup-Code noch nicht notiert – ohne ihn sind die Daten bei Verlust des Handys weg.',
    bannerOld: 'Seit über 7 Tagen kein Backup! Bitte Internetverbindung prüfen.',
    open: 'Öffnen',
    restoreLink: 'Neues Handy? Daten aus Backup wiederherstellen',
    restoreTitle: 'Aus Backup wiederherstellen',
    restoreHint: 'Gib deinen Backup-Code ein. Danach sind alle Patientinnen, Besuche und Rechnungen wieder da.',
    restoreCode: 'Backup-Code',
    restoreSubmit: 'Wiederherstellen',
    restoreNotEmpty: 'Auf diesem Gerät sind schon Daten. Wiederherstellen geht nur auf einem leeren Gerät.',
    restoreBadCode: 'Dieser Code ist nicht gültig. Bitte prüfe ihn.',
    restoreNotFound: 'Zu diesem Code wurde kein Backup gefunden.',
    restoreFailed: 'Wiederherstellen fehlgeschlagen (offline?).',
    restored: (n: number, when: string) => `Wiederhergestellt: ${n} Einträge, Stand ${when}.`,
  },
  practice: {
    title: 'Praxisdaten (für Rechnungen)',
    name: 'Name / Praxisname',
    ik: 'IK-Nummer',
    taxNote: 'Steuerhinweis',
    iban: 'IBAN',
    bank: 'Bank',
    saved: 'Gespeichert.',
  },
  child: { newTitle: 'Neues Kind', editTitle: 'Kind bearbeiten' },
  note: { newTitle: 'Neue Notiz', editTitle: 'Notiz bearbeiten' },
  fields: {
    personal: 'Persönliche Daten',
    firstName: 'Vorname',
    lastName: 'Nachname',
    dateOfBirth: 'Geburtsdatum',
    street: 'Straße und Hausnummer',
    postcode: 'PLZ',
    city: 'Ort',
    phone: 'Telefon',
    email: 'E-Mail',
    insuranceType: 'Versicherungsart',
    insurerName: 'Krankenkasse / Versicherung',
    insuranceNumber: 'Versichertennummer',
    pregnancy: 'Schwangerschaft',
    dueDate: 'Errechneter Termin (ET)',
    services: 'Gewünschte Leistungen',
    preferredContact: 'Bevorzugter Kontaktweg',
    message: 'Nachricht',
    status: 'Status',
    date: 'Datum',
    startTime: 'Beginn',
    endTime: 'Ende',
    location: 'Ort des Kontakts',
    seen: 'Betreut wurde',
    whichChild: 'Welches Kind',
    phase: 'Betreuungsphase',
    bp: 'Blutdruck (z. B. 120/80)',
    pulse: 'Puls',
    temp: 'Temperatur (°C)',
    weightKg: 'Gewicht (kg)',
    weightG: 'Gewicht (g)',
    feeding: 'Ernährung',
    childNotes: 'Notizen zum Kind',
    notes: 'Notizen',
    travelKm: 'Wegstrecke (km)',
    travelShared: 'Tour',
    travelSharedOn: 'mit mehreren Frauen (anteilig)',
    childName: 'Name',
    sex: 'Geschlecht',
    birthDate: 'Geburtsdatum',
    birthTime: 'Geburtszeit',
    birthWeightG: 'Geburtsgewicht (g)',
    lengthCm: 'Länge (cm)',
    headCm: 'Kopfumfang (cm)',
    apgar1: 'APGAR 1 Min.',
    apgar5: 'APGAR 5 Min.',
    apgar10: 'APGAR 10 Min.',
    birthMode: 'Geburtsmodus',
    placeOfBirth: 'Geburtsort',
    childInsurer: 'Krankenkasse des Kindes',
    childInsuranceNumber: 'Versichertennummer des Kindes',
    text: 'Text',
    required: 'Bitte ausfüllen',
  },
  options: {
    insuranceType: { statutory: 'Gesetzlich', private: 'Privat' },
    services: {
      pregnancy: 'Schwangerenvorsorge',
      birthPrep: 'Geburtsvorbereitungskurs',
      postpartum: 'Wochenbettbetreuung',
      breastfeeding: 'Stillberatung',
      recovery: 'Rückbildungskurs',
    },
    preferredContact: { phone: 'Telefon', email: 'E-Mail', sms: 'SMS' },
    status: { pending: 'Neu', active: 'In Betreuung', archived: 'Archiv' },
    location: { home: 'Hausbesuch', practice: 'Praxis', video: 'Video', phone: 'Telefon' },
    seen: { mother: 'Mutter', child: 'Kind', both: 'Mutter und Kind' },
    phase: { pregnancy: 'Schwangerschaft', birth: 'Geburt', postpartum: 'Wochenbett' },
    sex: { female: 'weiblich', male: 'männlich', diverse: 'divers' },
    birthMode: { spontan: 'Spontan', vaginal_op: 'Vaginal-operativ', sectio: 'Kaiserschnitt' },
    placeOfBirth: { clinic: 'Klinik', birthCenter: 'Geburtshaus', home: 'Hausgeburt' },
  },
  settings: {
    title: 'Einstellungen',
    changePassword: 'Passwort ändern',
    oldPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort',
    passwordChanged: 'Passwort geändert.',
    wrongPassword: 'Aktuelles Passwort ist falsch.',
    diagnostics: 'Diagnose exportieren',
    diagnosticsHint: 'Enthält nur App-Version, Fehler und Anzahl der Einträge – keine Patientendaten.',
    wipe: 'Alle Daten auf diesem Gerät löschen',
    wipeConfirm: 'Zum Bestätigen LÖSCHEN eingeben',
    wipeWord: 'LÖSCHEN',
    autoLock: 'Automatische Sperre nach 5 Minuten Inaktivität.',
  },
} as const;

export const t = de;
