// All UI text lives here so an English file can be added later with the same keys.
export const de = {
  appName: 'Spermio',
  common: {
    continue: 'Weiter',
    cancel: 'Abbrechen',
    back: 'Zurück',
    lock: 'Sperren',
    save: 'Speichern',
    working: 'Einen Moment …',
  },
  install: {
    title: 'App zum Home-Bildschirm hinzufügen',
    intro: 'Patientendaten werden nur auf diesem Gerät gespeichert. Damit Safari sie nicht automatisch löscht, muss die App installiert sein.',
    iosSteps: [
      'Tippe unten in Safari auf das Teilen-Symbol (Quadrat mit Pfeil).',
      'Wähle „Zum Home-Bildschirm“.',
      'Öffne die App danach über das neue Symbol auf dem Home-Bildschirm.',
    ],
    otherSteps: [
      'Öffne das Browser-Menü.',
      'Wähle „App installieren“ bzw. „Zum Startbildschirm hinzufügen“.',
      'Öffne die App danach über das neue Symbol.',
    ],
    testAnyway: 'Nur testen, ohne Installation (keine echten Daten!)',
    notInstalledBanner: 'Testmodus im Browser – keine echten Patientendaten eingeben.',
  },
  setup: {
    title: 'Willkommen',
    intro: 'Lege ein App-Passwort fest. Es schützt alle Daten auf diesem Gerät.',
    password: 'App-Passwort',
    passwordRepeat: 'Passwort wiederholen',
    tooShort: 'Mindestens 10 Zeichen.',
    mismatch: 'Die Passwörter stimmen nicht überein.',
    create: 'Passwort festlegen',
  },
  recovery: {
    title: 'Dein Wiederherstellungscode',
    intro: 'Wenn du dein Passwort vergisst, ist dieser Code der einzige Weg zurück an deine Daten. Niemand sonst – auch nicht der Entwickler – kann sie wiederherstellen.',
    howTo: 'Drucke den Code aus oder schreibe ihn ab und bewahre ihn sicher auf (nicht nur auf diesem Handy).',
    copy: 'Code kopieren',
    copied: 'Kopiert',
    print: 'Drucken',
    confirmCheck: 'Ich habe den Code ausgedruckt oder sicher aufgeschrieben.',
    verifyLabel: (n: number) => `Zur Kontrolle: Gib den ${n}. Block des Codes ein`,
    verifyWrong: 'Dieser Block stimmt nicht. Bitte prüfe deine Notiz.',
  },
  persist: {
    denied: 'Achtung: Der Browser hat dauerhaften Speicher abgelehnt. Daten könnten bei Speichermangel gelöscht werden. Erstelle regelmäßig Backups.',
  },
  unlock: {
    title: 'Gesperrt',
    password: 'App-Passwort',
    submit: 'Entsperren',
    wrong: 'Falsches Passwort.',
    forgot: 'Passwort vergessen?',
  },
  recover: {
    title: 'Mit Wiederherstellungscode entsperren',
    code: 'Wiederherstellungscode',
    newPassword: 'Neues App-Passwort',
    submit: 'Entsperren und Passwort ändern',
    wrong: 'Dieser Code ist nicht gültig.',
  },
  home: {
    title: 'Übersicht',
    patients: 'Patientinnen',
    empty: 'Noch keine Patientinnen. Lade Demo-Daten, um die App auszuprobieren.',
    loadDemo: 'Demo-Daten laden',
    demoLoaded: (n: number) => `${n} Demo-Patientinnen angelegt.`,
    dueDate: 'ET',
    visits: (n: number) => (n === 1 ? '1 Besuch' : `${n} Besuche`),
    children: (n: number) => (n === 1 ? '1 Kind' : `${n} Kinder`),
    statuses: { pending: 'Neu', active: 'In Betreuung', archived: 'Archiv' },
  },
  settings: {
    title: 'Einstellungen',
    changePassword: 'Passwort ändern',
    oldPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort',
    passwordChanged: 'Passwort geändert.',
    wrongPassword: 'Aktuelles Passwort ist falsch.',
    diagnostics: 'Diagnose exportieren',
    diagnosticsHint: 'Enthält nur App-Version, Fehler und Anzahl der Einträge – keine Patientendaten.',
    wipe: 'Alle Daten auf diesem Gerät löschen',
    wipeConfirm: 'Zum Bestätigen LÖSCHEN eingeben',
    wipeWord: 'LÖSCHEN',
    autoLock: 'Automatische Sperre nach 5 Minuten Inaktivität.',
  },
} as const;

export const t = de;
